### ISSUE TITLE
Migration of signatures from Cuckoo

### ISSUE THREAD

**Issue by cccs-kevin** [kevoreilly/community#283]
I noticed that while CAPE does have ~ 670 signatures, there is a large number of Cuckoo signatures (~400), at least by looking at their names alone, that did not make it to CAPE. 

Obviously they could've been renamed when migrated, although I don't think that is the case. I'm wondering if there was a reason for a lot of signatures did not make it to CAPE?

A few examples of the signatures that did not make it: 
- [`amsi_bypass`](https://github.com/cuckoosandbox/community/blob/14864b9fa2ba2576ca11887caf37616eaec6d941/modules/signatures/windows/powershell.py#L60)
- [`antivm_parallels_window`](https://github.com/cuckoosandbox/community/blob/14864b9fa2ba2576ca11887caf37616eaec6d941/modules/signatures/windows/antivm_parallels_window.py#L19)
- [`creates_null_reg_entry`](https://github.com/cuckoosandbox/community/blob/14864b9fa2ba2576ca11887caf37616eaec6d941/modules/signatures/windows/creates_null_reg_entry.py#L9)

**Comment by kevoreilly** [comment]
I think there was some divergence in compatibility  from Cuckoo, such that porting would require some work. But certainly those examples sound like they would be worth having.

**Comment by cccs-kevin** [comment]
> I think there was some divergence in compatibility from Cuckoo, such that porting would require some work. But certainly those examples sound like they would be worth having.

Okay excellent, I'll work on the porting when I have some time :)
