### ISSUE TITLE
Get "several No module" errors and "permission denied"  when run cuckoo.py

### ISSUE THREAD

**Issue by alishaf** [kevoreilly/community#308]
Hi, Will be thankful to help me with this issue.

I installed and configure capev2 using its documentation. The OS is ubuntu 20.04 LTS.

There are some "no module named ..." errors and one permission error for:
PermissionError: [Errno 13] Permission denied: '/opt/CAPEv2/log/cuckoo.log'

This is the output of running python3 cuckoo.py in /opt/CAPEv2/:
(As an example, I tried to install BumbleBee by pip3, but the error is not solved.)

CAPE parser: No module named BumbleBee - No module named 'regex'
CAPE parser: No module named CobaltStrikeBeacon - No module named 'netstruct'
CAPE parser: No module named Blister - No module named 'malduck'

  .-----------------.
  | Cuckoo Sandbox? |
  |     OH NOES!    |\  '-.__.-'
  '-----------------' \  /oo |--.--,--,--.
                         \_.-'._i__i__i_.'
                               """""""""

 Cuckoo Sandbox 2.2-CAPE
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 CAPE: Config and Payload Extraction
 github.com/kevoreilly/CAPEv2

Traceback (most recent call last):
  File "cuckoo.py", line 118, in <module>
    cuckoo_init(quiet=args.quiet, debug=args.debug, artwork=args.artwork, test=args.test)
  File "cuckoo.py", line 76, in cuckoo_init
    init_logging(level)
  File "/opt/CAPEv2/lib/cuckoo/core/startup.py", line 176, in init_logging
    fh = logging.handlers.TimedRotatingFileHandler(
  File "/usr/lib/python3.8/logging/handlers.py", line 200, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/CAPEv2/log/cuckoo.log'

**Comment by doomedraven** [comment]
First of all wrong repo. Second you should run e everything as cape user

**Comment by doomedraven** [comment]
Google missed loader and what is bumblebee

**Comment by alishaf** [comment]
> First of all wrong repo. Second you should run e everything as cape user El vie, 29 jul 2022 16:57, alishaf ***@***.***> escribió:
> […](#)

Thank you for your help.
Firstly, what do you mean by the wrong repo?
Secondly, I logged in as cape user after reading your comment. Then when I start cuckoo it gives the first error I got when I executed with my own user. which is: "ERROR: Missing dependency: No module named 'gevent'"

When I executed cuckoo.py as my own user I got this error too. I solved the issues one by one and now I'm in the state I mentioned in the post.

Sorry if my questions are dumb.

**Comment by alishaf** [comment]
> 

Ok I solved the the "no modules ...".
I still have the permission issue. So shall I reinstall everything with cape user??

**Comment by doomedraven** [comment]
Google what is shown, and use ls and chown to change permissi9n, you should
run cape before with wrong user
