### ISSUE TITLE
Redundant execution in Procmon Auxiliary Module

### ISSUE THREAD

**Issue by oalieno** [kevoreilly/community#334]
https://github.com/kevoreilly/community/blob/8ecef0aa052b459c73b4ff8afb3048e589b9a5bb/analyzer/windows/modules/auxiliary/procmon.py#L66-L94

The check for `self.enabled` should be moved to the beginning of the function. Just like in the `run` function.
```python
def stop(self) -> bool: 
    if not self.enabled: 
        return return False
    ...
    return False 
```

Otherwise, `procmon.exe /Terminate` and `procmon.exe /OpenLog ...` will still be run, which is pointless?

**Comment by doomedraven** [comment]
thanks
